version: '2.3'
services:
    ipv6nat:
            restart: unless-stopped
            image: "us-docker.pkg.dev/omgwtfbbq/gcr.io/ipv6nat:2"
            privileged: true
            network_mode: "host"
            volumes:
                    - "/var/run/docker.sock:/var/run/docker.sock:ro"                                                           
                    - "/lib/modules:/lib/modules:ro"
    unbound:
            restart: unless-stopped
            image: "us-docker.pkg.dev/omgwtfbbq/gcr.io/unbound:1000e"
            runtime: runsc-kvm
            mem_limit: 4g
            networks:
                    omgwtfbbq:
                            ipv4_address: 172.19.1.50
            dns: 172.19.1.50
    wtf:
            restart: unless-stopped
            volumes:
                    - "/docker/resolv.conf:/etc/resolv.conf"
                    - "/usr/local/tmp:/usr/local/tmp"
            image: "us-docker.pkg.dev/omgwtfbbq/gcr.io/wtf-standalone:2.0.17"
            networks:
                    omgwtfbbq:
                            ipv4_address: 172.19.1.200
            dns: 172.19.1.50
            mem_limit: 8g
            ports:
              - "80:10080"
              - "443:10443"

    stun:
            restart: unless-stopped
            image: "us-docker.pkg.dev/omgwtfbbq/gcr.io/stun:1000c"
            runtime: runsc-kvm
            mem_limit: 256m
            networks:
                    omgwtfbbq:
                            ipv4_address: 172.19.1.150
            ports:
                    - "3478:3478/udp"
    redis:
            restart: unless-stopped
            image: "us-docker.pkg.dev/omgwtfbbq/gcr.io/redis:1000b"
            runtime: runsc-kvm
            mem_limit: 256m
            networks:
                    omgwtfbbq:
                            ipv4_address: 172.19.1.70
            dns: 172.19.1.50


networks:
        omgwtfbbq:
                external: true
