version: '2.3'
services:
    ipv6nat:
            restart: unless-stopped
            image: "gcr.io/omgwtfbbq/ipv6nat:2"
            privileged: true
            network_mode: "host"
            volumes:
                    - "/var/run/docker.sock:/var/run/docker.sock:ro"                                                           
                    - "/lib/modules:/lib/modules:ro"
    unbound:
            restart: unless-stopped
            image: "gcr.io/omgwtfbbq/unbound:101"
            runtime: runsc-kvm
            mem_limit: 4g
            networks:
                    omgwtfbbq:
                            ipv4_address: 172.19.1.50
            dns: 172.19.1.50
    wtf:
            restart: unless-stopped
            volumes:
                    - "/docker/resolv.conf:/etc/resolv.conf"
            image: "gcr.io/omgwtfbbq/wtf-standalone:3212"
            networks:
                    omgwtfbbq:
                            ipv4_address: 172.19.1.200
            dns: 172.19.1.50
            mem_limit: 8g
            ports:
                    - "80:10080"
                    - "443:10443"
    stun:
            restart: unless-stopped
            image: "gcr.io/omgwtfbbq/stun:10"
            runtime: runsc-kvm
            mem_limit: 512m
            networks:
                    omgwtfbbq:
                            ipv4_address: 172.19.1.150
            ports:
                    - "3478:3478/udp"
    redis:
            restart: unless-stopped
            image: "gcr.io/omgwtfbbq/redis:6"
            runtime: runsc-kvm
            mem_limit: 1g
            networks:
                    omgwtfbbq:
                            ipv4_address: 172.19.1.70
            dns: 172.19.1.50

networks:
        omgwtfbbq:
                external: true
